name: Release
on: [push]
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowJar
      - name: Get Version Number
        id: version-num
        run: |
          tag_name=${{github.ref_name}}
          echo "::set-output name=version-num::${tag_name:1:${#tag_name}}"
      - name: Release If Tagged
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          files: mcbomb/build/libs/mcbomb-${{steps.version-num.outputs.version-num}}-all.jar
